engines:
  checkstyle:
    enabled: true
    channel: "beta"
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript

ratings:
  paths:
  - src/main/java/**
  - webapp/css/main.css
  - webapp/css/media.css
  - webapp/css/style.css
  - webapp/css/styleguide.css
  - webapp/js/custom.js
  - webapp/js/ordertrack.js

